controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    cart_effort_controller:
      type: effort_controllers/JointGroupEffortController

cart_effort_controller:
  ros__parameters:
    joints:
      - cart_joint
